### ISSUE TITLE
request for code style configs

### ISSUE THREAD

**Issue by SignpostMarv** [goetas-webservices/xsd-reader#19]
- [x] a `.editorconfig` file would be handy for ensuring contributors have a consistent line ending/ indentation style (or at least those that use an editor supporting it) **- handled in #20**
- [ ] having a config file for `friendsofphp/php-cs-fixer` would allow you to have a reasonably well defined code style which if defined as it's own composer package could be shared amongst all of your packages ([here's one I made earlier](https://github.com/SignpostMarv/PHP-CS-Fixer-Config))
- * [ ] adding `@Symfony` with yoda conditions disabled.

If we're going with a php-cs-fixer config, I'd suggest going beyond a base symfony/psr-2 style & [browsing the available rules](https://github.com/FriendsOfPHP/PHP-CS-Fixer), since there's some rules that aren't part of the "standard" sets, or there might be some rules you don't like (i.e. if you think yoda conditions are weird) that could be turned off.

**Comment by goetas** [comment]
I like both ideas. the project started small and did not think about it.

**Comment by SignpostMarv** [comment]
editorconfig is being handled in #20, so for php-cs-fixer I'm thinking the process would be this:

- pick a bunch of rulesets & rule configs
- drop the definition into a new branch split from master (I can take care of the grunt work there)
- apply fixes to master
- I merge the definition onto the static-analysis branch (rebasing will probably be a pain, so it'll probably be a cherry-pick of the definition commit)
- at some point in the future, you fork the definition off into it's own repo so the config can be shared among all the packages ?

So... as for php-cs-fixer, I'd invite you to peruse the linked docs to review the impact of enabling/disabling particular rulesets & rules.

- [ ]  friendsofphp/php-cs-fixer currently requires a minimum of php 5.6, so as with phpstan & psalm on the static analysis branch, the initial fork should advise installing it globally until such a time as either the static-analysis pull request is successful, or some other commit is pulled in that raises the minimum level to 5.6 (i.e. variadic/expansion syntax)
- [Rulesets](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/ab2e189d94698178988f9732bc75bb4ce8d16f77/src/RuleSet.php)
- * [ ] [@PSR-1](http://www.php-fig.org/psr/psr-1/)
- * [ ] [@PSR-2](http://www.php-fig.org/psr/psr-2/) - the psr-1 ruleset is bundled with the psr-2 ruleset, so unless you have objections, I'd be leaning towards making this the bare minimum
- * [ ] [@Symfony](http://symfony.com/doc/current/contributing/code/standards.html) this has some rules in that make some minor readability improvements (such as enforcing spaces around certain operators), but also has some things that might be a little bit odd (such as yoda conditions)
- * [ ] `@Symfony:risky` this has some rules that can break functionality but may not apply, i.e. I don't think you'd be affected by the ereg_to_preg rule, such as the phpunit-related rules (not sure how it'd react to the tests written for 4.x that were upgraded to ^5.7 on the static-analysis branch)
- * [ ] `@DoctrineAnnotation` is likely irrelevant, unless you've got doctrine-related projects ?
- * [ ] `@PHP56Migration`, `@PHP56Migration:risky` as with doing a `require-dev` of friendsofphp/php-cs-fixer, these are moot for now, since we're still keeping the 5.4 mnimum?
- * [ ] `@PHP70Migration`, `@PHP70Migration:risky`, `@PHP71Migration`, and `@PHP71Migration:risky` are all currently irrelevant, until I get the [php-7.1 branch](https://github.com/SignpostMarv/xsd-reader/tree/php-7.1) finished or you otherwise drop support for php 5.
- [Individual Rules](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.7.1/README.rst#usage)
- * [ ] align_multiline_comment - I'm guessing this one would be a yes, since the majority of the comments are asterisk-aligned already.
- * [ ] array_syntax - this can safely be set to either `long` or `short`, so it's a case of pick your preference
- * [ ] class_keyword_remove - this is another one currently only has relevance to the static-analysis branch; my preference is for `::class`, although enabling it may come in handy anywhere `AttributeGroup::class` and `Group::class` are used, since both would be expanded to `'GoetasWebservices\XML\XSDReader\Schema\Attribute\Group'` and `'GoetasWebservices\XML\XSDReader\Schema\Element\Group'` respectively, regardless of which namespace they were being used in.
- * [ ] combine_consecutive_issets - for `isset($foo, $bar, $baz)` instead of `isset($foo) && isset($bar) && isset($baz)`
- * [ ] combine_consecutive_unsets - similar to combine_consecutive_issets
- * [ ] general_phpdoc_annotation_remove - lets you define a list of annotations to be removed from doc blocks.
- * [ ] header_comment - useful for boilerplate comments, I guess ?
- * [ ] heredoc_to_nowdoc - possibly not useful on this project, but also not usable until we shift from 5.4 to 5.6 as a minimum.
- * [ ] linebreak_after_opening_tag - avoids `<?php // lolwhut`
- * [ ] list_syntax - only relevant for php 7.1 as a minimum support level
- * [ ] mb_str_functions might be useful since the XSD feeds can be utf-8 ? (swaps `strlen() for `mb_strlen()` etc.)
- * [ ] native_function_invocation - this is a code optimisation thing, see [without](https://3v4l.org/8OZUD/vld#output) vs. [with](https://3v4l.org/E83em/vld#output) - the downside to enabling this rule is reviewing large diffs when it's applied to code that doesn't already have it enabled.
- * [ ] no_blank_lines_before_namespace - code style
- * [ ] no_multiline_whitespace_before_semicolons -  this one affects code like this:
```php
echo
    'foo',
    'bar'
;
```
moving the semicolon, `'bar';`
- * [ ] no_null_property_initialization - code style thing.
- * [ ] no_php4_constructor - possibly a bit redundant since PHP 4 isn't supported and most contributors will likely be used to `__construct()` already.
- * [ ] no_short_echo_tag - code style thing, probably not relevant on this project
- * [ ] no_superfluous_elseif - another code style thing
- * [ ] no_unreachable_default_argument_value - this one is for deprecating the ability to `function ($foo = null, $bar) {` - it comes up on one of my the old php 5.6 projects at work that has a router with `function (Request $request, Response & $response = null, array $someOtherStuffThatIForget)`, where in PHP < 7.1 you'd re-order the parameters and in php >= 7.1, you'd `function (Request $request, ? Response $response, array $etc)` - entirely optional & probably not an issue on this project, I think.
- * [ ] no_useless_else - this one is handy for dropping else blocks with when there's returns earlier up the if-elseif chain
- * [ ] no_useless_return - this one is handy when combined with `blank_line_before_return`, since it'd remove 1 "useless" return line instead of adding a blank line.
- * [ ] not_operator_with_space & not_operator_with_successor_space - these ones may or may not bug you. `if (!isset($ruleTurnedOfff))` vs. `if ( ! isset($ruleTurnedOn))`
- * [ ] ordered_class_elements - this one is an organisational one, rearranging large blocks of code, so if enabled we'd want to apply it to the ruleset after all the other rules have been applied, so we can see the effects of the other rules more clearly.
- * [ ] ordered_imports - organisational, sort import statements by alphabet or line length.
- * [ ] php_unit_strict, php_unit_test_class_requires_covers - these affect the tests, not the main source.
- * [ ] phpdoc_add_missing_param_annotation - this is something I did manually in the static-analysis branch when resolving issues for phpstan & psalm
- * [ ] phpdoc_order, phpdoc_types_order - organisational, gives docblocks a consistent order.
- * [ ] psr0 - i was sure this used to be bundled with one of the rulesets, but it's not listed as such in the docs 😕 
- * [ ] simplified_null_return - this one is only a pain in the neck when you shift to php 7.1 and have methods that conditionally return null (my own config package has a sub-ruleset that turns it off)
- * [ ] single_line_comment_style - code style
- * [ ] strict_comparison this one can break things, especially when dealing with loosely typed stuff; `$foo == 1` is functionally equivalent when `$foo` is `1` or `'1'`, but it's no the case with `$foo === 1`. this is one that *should* be picked up by tests, if enabled.
- * [ ] strict_param - as with strict_comparison, this can break things but *should* be picked up by tests

**Comment by goetas** [comment]
Hi, thanks again for your efforts. 
Actually I'm not very picky with coding standards.. what about picking the "symfony" standards (possibly excluding the yoda-conditions)?

Is there any other rule you suggest to add?

**Comment by SignpostMarv** [comment]
a lot of the rules I didn't initially like myself, but then I got used to them.

I'd be interested to see what the effects are of the mb rules, but that would most likely require packages that do tests on multi-byte unicode content, rather than the simpler end of things.

**Comment by goetas** [comment]
resolved in https://github.com/goetas-webservices/xsd-reader/pull/21
