### ISSUE TITLE
re-enabling code coverage for scrutinzer

### ISSUE THREAD

**Issue by SignpostMarv** [goetas-webservices/xsd-reader#28]
back in the static-analysis branch, I'd enabled tests & code coverage to run internally, but it was turned off at your request- we've seen recently that scrutinizer inspections have failed because it was waiting for code coverage from travis.

I've currently got a branch ready for re-enabling psalm tests on xsd-reader, but it's been stuck for 2 hours on the code coverage element.

Any chance we can re-enable tests & code coverage on scrutinizer?

**Comment by goetas** [comment]
Do not  understand... I see the code coverage... https://scrutinizer-ci.com/g/goetas-webservices/xsd-reader/?branch=master currently 88%... isnt?

**Comment by SignpostMarv** [comment]
I'm referring to things like [this](https://scrutinizer-ci.com/g/goetas-webservices/xsd-reader/inspections/1ff63dff-7b7f-46cd-832a-177994fd5fcb) and [this](https://scrutinizer-ci.com/g/SignpostMarv/xsd-reader/inspections/c52d2b3a-acbf-49d8-ac32-a89ac9e603d3)

**Comment by goetas** [comment]
when a travis ci job fails, code coverage is not sent.
do not want to maintain builds both on scrutinizer and on travis. 

(if you want to have code coverage while developing locally you can run phpunit locally)

**Comment by goetas** [comment]
here https://scrutinizer-ci.com/g/SignpostMarv/xsd-reader/inspections/c52d2b3a-acbf-49d8-ac32-a89ac9e603d3 code coverage was sent, but  looks the build on scrutinizer failed

**Comment by SignpostMarv** [comment]
@goetas this is less about having the code coverage available on scrutinizer and more about not letting travis hold up a scrutinizer inspection & have it fail because travis didn't send information in a timely fashion.

**Comment by Guite** [comment]
Scrutinizer is not used anymore. CI is running with GitHub actions now. Hence I will close this one.
