### ISSUE TITLE
Having issues finding the default value

### ISSUE THREAD

**Issue by mquinn123** [goetas-webservices/xsd-reader#34]
So I am parsing out a xsd file and everything is working awesome. 

But I don't see anyway to grab the default value.

``
<xsd:element default="2000" maxOccurs="1" minOccurs="1" name="port" nillable="false" type="integer"/>
``

Is there anyway to find that default value of 2000?

**Comment by mquinn123** [comment]
So I forked an added the functionality to get the default value. Its untested at the moment but if you want I can setup a PR.

**Comment by goetas** [comment]
Yes, pr are always welcome

**Comment by goetas** [comment]
Thanks

**Comment by goetas** [comment]
Solved by https://github.com/goetas-webservices/xsd-reader/pull/35
