### ISSUE TITLE
Choise tag in ComplexType

### ISSUE THREAD

**Issue by judimator** [goetas-webservices/xsd-reader#5]
Hello. I have a few problem with parse XSD.  The first is SchemaReader Class doesn't have a opportunity to parse totalDigits, fractionDigits restriction. Becouse of that I create own class with almost content. And the second is ComplexType with choise tag parses like sequence, but didn't. Thanks.

**Comment by goetas** [comment]
Yes both limitations are known. Pull requests are welcme

**Comment by judimator** [comment]
Goetas, I see, that you have added a choice detection. But how can I use it, and add please totalDigits, fractionDigits to loadRestriction method. Thanks.

**Comment by goetas** [comment]
soon there will bea lot of improvements, this because some PR has been merged to the serializer.

**Comment by judimator** [comment]
When wait for update?:)

**Comment by goetas** [comment]
when JMS serializer 1.2 will be tagged

**Comment by TheSachin** [comment]
Any status update on this?

**Comment by goetas** [comment]
Regarding the choice vs sequence, currently there is no easy way to do it simply because php classes do not have that principle. Something could be done by validating the object (stared here and never finished https://github.com/goetas-webservices/xsd2php/pull/2)

**Comment by goetas** [comment]
Total digits and fraction digits have not been implemented yet :(

**Comment by Guite** [comment]
Proper choice support has been added in 0.4.0.
Also there is a new enum called `RestrictionType` that should allow you to work with both total digits and fraction digits.
