### ISSUE TITLE
ComplexType mixed="true"

### ISSUE THREAD

**Issue by marcuskober** [goetas-webservices/xsd-reader#50]
Hi there,

is there a way to determine if a complex type has mixed set to true?

```
<xsd:complexType mixed="true">
...
</xsd:complexType>
```

**Comment by goetas** [comment]
See https://github.com/goetas-webservices/xsd2php/issues/99#issuecomment-550447364

**Comment by marcuskober** [comment]
Thank you.

For my use case (reading OpenImmo xsd) I created a new Type ComplexTypeMixed:

`<?php

declare(strict_types=1);

namespace GoetasWebservices\XML\XSDReader\Schema\Type;

class ComplexTypeMixed extends ComplexType
{
}
`

Then added following in SchemaReader.php after line 527:

`        if ($node->hasAttribute('mixed') && $node->getAttribute('mixed')) {
            $type = new ComplexTypeMixed($schema, $node->getAttribute('name'));
        }
`

I'm using your xsd reader to create classes for deserializing with JSM serializer lib. The class created out of those ComplexTypeMixed elements gets a property of type string and name "value".  The type for JSM is Annotation\Inline:

`
	/**
	 * @inline 
	 * @Type("string") 
	 * @var string
	 */
	protected $value;
`
As mentioned - for my use case this workaround works...

**Comment by mgrundkoetter** [comment]
@marcuskober I applied your patch into the branch https://github.com/ujamii/openimmo/tree/bugfix/issue-3
If you have time, can you please try it out with some real data? If everything works, I would like to merge this into the master. I only have 2 sample files, so my tests are very limited :-(

**Comment by Guite** [comment]
In version 0.4.0 you can use `ComplexType#isMixed()`.
Closing as fixed.
