### ISSUE TITLE
UrlUtils::replaceSuperfluousSlashes incorrectly handles multiple sets

### ISSUE THREAD

**Issue by steve962** [goetas-webservices/xsd-reader#55]
I was trying to parse a complex XSD hierarchy using the NIEM 4.2 standard which uses a number of subdirectories and multiple relative path levels, and it was failing to find many of the files.   I tracked the problem down to the src/Utils/UrlUtils.php module, where the static method replaceSuperfluousSlashes() was the culprit.   Given a path like:

```/home/username/docs/xsd/level1a/level2a/level3a/../../../level1b/somefile.xsd```

...you would expect it to return:

```/home/username/docs/xsd/level1b/somefile.xsd```

...but instead it returns:

```/home/username/docs/xsd/level1a/level2a/level1b/somefile.xsd```

I resolved the problem in my situation by adding the following code to the beginning of the function:

```php
        $rp = realpath($abs);
        if ($rp) {
            return $rp;
        }
```

...but I'm not sure if that's the right fix for every case, since I'm not sure why realpath() wasn't used in the first place.

**Comment by goetas** [comment]
hmm, i'm open for fixing this. can you provide a PR?
