### ISSUE TITLE
Request to support multi language xs:documentation annotations

### ISSUE THREAD

**Issue by zambodaniel** [goetas-webservices/xsd-reader#58]
Currently, if there are multiple language documentation tags in an annotation, they are concatenated together in one single line.
See attached screenshots. I'll submit a PR to resolve this, by adding a line break if there are multiple docs for a node.

![Screenshot from 2020-10-16 11-43-55](https://user-images.githubusercontent.com/3462880/96243383-f9818400-0fa4-11eb-866c-d09c4c76afff.png)
![Screenshot from 2020-10-16 11-44-26](https://user-images.githubusercontent.com/3462880/96243393-fbe3de00-0fa4-11eb-9de5-9e6e9298821e.png)

**Comment by goetas** [comment]
https://github.com/goetas-webservices/xsd-reader/pull/59 has been merged
